export default {
  SET_BOOKS: 'SET_BOOKS',
  SET_TOTAL_RESULTS: 'SET_TOTAL_RESULTS',
  SET_RESULT_TYPE: 'SET_RESULT_TYPE',
  ADD_TO_WISHLIST: 'ADD_TO_WISHLIST',
  SET_WISHLIST: 'SET_WISHLIST',
  SET_CURRENT_BOOK: 'SET_CURRENT_BOOK',
};